use crate::state::State;
use anyhow::{Context, Result};
use std::fs;

pub fn update_hyprlock_config(state: &State) -> Result<()> {
    let config_dir = dirs::config_dir()
        .context("Could not find config directory")?
        .join("hypr");
    let lock_conf_path = config_dir.join("hyprwallhaven-hyprlock.conf");

    let mut content = String::from("# Auto-generated by hyprwallhaven\n\n");

    for (monitor, path) in &state.wallpapers {
        content.push_str("background {\n");
        content.push_str(&format!("    monitor = {}\n", monitor));
        content.push_str(&format!("    path = {}\n", path));
        content.push_str("    color = rgba(25, 20, 20, 1.0)\n");
        content.push_str("    blur_passes = 0\n"); 
        content.push_str("}\n\n");
    }

    // Add a fallback for unconfigured monitors?
    // Maybe not, to avoid overriding user's manual config if they mix and match.
    // But usually people want coverage.
    // Let's stick to explicit monitors we know about.

    fs::write(&lock_conf_path, content)?;
    Ok(())
}
